### ISSUE TITLE
No container updates

### ISSUE THREAD

**Issue by vuolter** [pyload/updatemanager#18]
DLC guys claim my head! Hurry, I'm running away in the meantime... :P

**Comment by stickell** [comment]
The issue is related to the plugin!
These were `.pyc` files to protect the source code. The update manager tries to delete them as `.py`. Take a look at this line:
https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/UpdateManager.py#L285

**Comment by vuolter** [comment]
and .pyc: https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/UpdateManager.py#L296. ;)
No DLC.py or any container plugins are in the server response http://updatemanager.pyload.org/?v=0.4.9

**Comment by stickell** [comment]
Oh sorry, I haven't understood that the issue is that the server is not indexing the container folder.
I was referring to pyload/pyload#1089 and #19.

**Comment by stickell** [comment]
Resolved. Sorry I'm a bit out of shape

**Comment by vuolter** [comment]
No worries, Stefano. I'm a bit tired too. :D
