### ISSUE TITLE
Updatemanager error removing

### ISSUE THREAD

**Issue by Mister-XY** [pyload/updatemanager#19]
Hello, i have in debugging mode many message like this "UpdateManager: Error removing: XFSPAccount.py | [Errno 2] No such file or directory: 'userplugins/internal/XFSPAccount.py'" or this "UpdateManager: Error removing: DLC_25.py | [Errno 2] No such file or directory: 'userplugins/container/DLC_25.py' "
There are also other files. 
Best regards

**Comment by stickell** [comment]
This issue is related to the update manager client plugin but this is the repository of the server software. You have to report this issue under pyload/pyload.
