### ISSUE TITLE
Git local copy stucks

### ISSUE THREAD

**Issue by stickell** [pyload/updatemanager#20]
Sometimes the local copy on the server goes to merge conflict (even if nobody changes the files there!) probably due to a failure during pulling. When this happen the application is no more able to detect updates.

When it will happen again try to apply the fix in the `pull_fix` branch.

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/issues/1101

**Comment by stickell** [comment]
Git repo was fine this time. The trouble was that GitHub hasn't been able to trigger the webhook of the update process cause of `Invalid host name`. Maybe the guys at Openshift had some problems with the DNS. I've asked GitHub to redeliver the payload and now it has succeeded.

**Comment by stickell** [comment]
Merged. Let's hope it will never happen again
