### ISSUE TITLE
captcha|UlozTo.py has no version

### ISSUE THREAD

**Issue by GammaC0de** [pyload/updatemanager#39]
Hi,
captcha|UlozTo.py was merged without a `__version__` string.
This caused captcha|UlozTo.py in http://updatemanager.pyload.org/?v=0.4.9 to not have a version number in it either.
Pushing another version with  a `__version__` string does not make any change.

Please advise.

**Comment by Ryan747800B** [comment]
@GammaC0de Issue is probably [here;](http://updatemanager.pyload.org/?v=0.4.9) as you can see, `UlozTo` hasn't version number.

```
captcha|SolveMedia.py|93192da|0.18
captcha|UlozTo.py|e4fc68f|
container|CCF.py|fd4ff4e|0.28
```

I tried to download that html, delete line 186 (`UlozTo`) and modify `UpdateManager.py`, so it redirects to a modded `UpdateMnanager.html` but it doesn't work. All done with a fresh install.

**Comment by GammaC0de** [comment]
@Ryan747800B I know that
The problem is I don't have permissions to change it, only @stickell has.

**Comment by Ryan747800B** [comment]
@GammaC0de No way to contact him? In addition, is there a way to bypass that file, maybe hosting it on a local server?

**Comment by GammaC0de** [comment]
@Ryan747800B: @stickell reads the posts here, it just take some time because he is busy.
Anyway, `UpdateManager` v1.11 already handles this situation, just `UlozTo`is not beeing updated.
https://github.com/pyload/pyload/raw/stable/module/plugins/hooks/UpdateManager.py

**Comment by stickell** [comment]
Should be fixed
