### ISSUE TITLE
UploadedTo showing as not premium in Pyload

### ISSUE THREAD

**Issue by thermalhack** [pyload/updatemanager#40]
Hello,

I am struggling with Pyload on my Raspberry Pi B. I installed Pyload which seems to be working fine, however updates do not work unless I find a new copy of UpdateManager.py. However my main issue is that when I load my UploadedTo credentials into Pyload, it tells me that it is not a premium account and all UploatedTo links I download end after a few KB and not correctly named.

I have tried this on a Noobs install of rRasbian, both wheezy and jessie, and both on Pyload 4.9 & 4.8. Sam symptoms on both.

My UploadedTo account works perfectly on the UploadedTo website and on Jdownloader. Please can someone help?

Thank you

**Comment by GammaC0de** [comment]
Not related to updatemanager
