### ISSUE TITLE
Update server is down

### ISSUE THREAD

**Issue by GammaC0de** [pyload/updatemanager#41]
http://updatemanager.pyload.org/
![pyload org_-_2016-05-21_18 22 46](https://cloud.githubusercontent.com/assets/11036551/15449248/13ba997e-1f81-11e6-87fa-2c65e3f85098.png)

**Comment by stickell** [comment]
The server is fine, the issue is related to the domain expire.
You can use the original Openshift host name: http://updatemanager-spyload.rhcloud.com/?v=0.4.9
