### ISSUE TITLE
blacklist.txt not pushed to the update server

### ISSUE THREAD

**Issue by GammaC0de** [pyload/updatemanager#42]
Hi @vuolter @stickell ,

I have updated `blacklist.txt` (added `UploadableCh.py` to the blacklist https://github.com/pyload/updatemanager/commit/c0c185705651773911bd3e68bd5b51187003d9fa) but on the server the blacklist is not changing (https://updatemanager-spyload.rhcloud.com/?v=0.4.9)

Am I doing something wrong?

**Comment by vuolter** [comment]
@GammaC0de Sometimes the server needs to be restarted, that is what @stickell said to me.

**Comment by vuolter** [comment]
@GammaC0de I just have send an email to @stickell ;)

**Comment by GammaC0de** [comment]
@vuolter :+1: 
By the way, what is the status of the update server in v0.5? 
Will it still work the same way (with update server)? or maybe it will work directly from the git repo?

**Comment by vuolter** [comment]
Directly on the repo, using the github etag to determine if there're new changes. ;)
