### ISSUE TITLE
Looking  for @vuolter 

### ISSUE THREAD

**Issue by GammaC0de** [pyload/updatemanager#43]
Hi @stickell 
@vuolter has not been active since 2 month,
He did not said anything about a vacation or something like that,
He is not responding to github messages,
I am worried..

Can you try to contact him please?

**Comment by GammaC0de** [comment]
@stickell @vuolter ??

**Comment by stickell** [comment]
Hi @GammaC0de,
I have no private informations about @vuolter. I can try to contact him but I'm sure he is still receiving this updates.

**Comment by GammaC0de** [comment]
@stickell Please do,
Last time he was active is 4'th of July..

**Comment by vuolter** [comment]
@GammaC0de I am safe and sound, if anyone had doubts about that. :stuck_out_tongue_winking_eye:
I'm sorry I made you worry. :cry:
In last months I was able to connect to the web only for few moments... but now that I'm finally back home, I can resume to work on the project (at least for a couple of weeks). Last time I was "playing" with pyLoad was in August, approximately, and there was still some routines to fix and test. :persevere:
For now I have just a loooot of messages to reply, but I'm truly back, fellows! :grin:

**Comment by GammaC0de** [comment]
Hey @vuolter Welcome back!! :tada:

I remember exactly the date: 4th of july: you said "pyLoad v0.5 in very soon" and then vanished for three month without warning... :worried:
I was really worried: three month without any email / commit / issue comment /  tweet / nothing!

Well, for now, for the sake of pyLoad, I really think that you MUST upload your work to Github AS-IS, without waiting no more..
Not having it online it quite a risk of loosing one year of coding...

I hope you understand me..

**Comment by vuolter** [comment]
I understand your point. I will try to upload all, but I have to revert some stuff to get a working release. u.u
Firstly, I really have to respond to the hundreds of emails in my mailboxes, then I'll check the remote repo here on github, sync it with mine ad so on. 😨
